#
# Auto-generated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require "rubygems"
require "thrift"
require "./blob_types"
require "./cloud_blob_client_types"
require "./cloud_blob_container_types"
require "./cloud_file_types"
require "./cloud_file_client_types"
require "./cloud_file_directory_types"
require "./cloud_file_share_types"
require "./cloud_queue_types"
require "./cloud_queue_client_types"
require "./cloud_table_types"
