#
# Auto-generated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require "rubygems"
require "thrift"
require_relative "core_types"
require_relative "queue_types_types"


module Azure
  module Storage
    module AutoGenerated
      class ListQueuesPayload
        include ::Thrift::Struct, ::Thrift::Struct_Union
        PREFIX = 1
        DETAILSINCLUDED = 2
        REQUESTOPTIONS = 3
        THRIFTOPERATIONCONTEXT = 4

        FIELDS = {
          PREFIX => { type: ::Thrift::Types::STRING, name: "prefix", optional: true },
          DETAILSINCLUDED => { type: ::Thrift::Types::I32, name: "detailsIncluded", optional: true, enum_class: ::Azure::Storage::AutoGenerated::ThriftQueueListingDetails },
          REQUESTOPTIONS => { type: ::Thrift::Types::STRUCT, name: "requestOptions", class: ::Azure::Storage::AutoGenerated::ThriftQueueRequestOptions, optional: true },
          THRIFTOPERATIONCONTEXT => { type: ::Thrift::Types::STRUCT, name: "thriftOperationContext", class: ::Azure::Storage::AutoGenerated::OperationContext, optional: true }
        }

        def struct_fields; FIELDS; end

        def validate
          unless @detailsIncluded.nil? || ::Azure::Storage::AutoGenerated::ThriftQueueListingDetails::VALID_VALUES.include?(@detailsIncluded)
            raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, "Invalid value of field detailsIncluded!")
          end
        end

        ::Thrift::Struct.generate_accessors self
      end

      class ListQueuesResponse
        include ::Thrift::Struct, ::Thrift::Struct_Union
        QUEUELIST = 1
        CONTINUATIONTOKEN = 2

        FIELDS = {
          QUEUELIST => { type: ::Thrift::Types::LIST, name: "queueList", element: { type: ::Thrift::Types::STRUCT, class: ::Azure::Storage::AutoGenerated::CloudQueueResponse } },
          CONTINUATIONTOKEN => { type: ::Thrift::Types::STRUCT, name: "continuationToken", class: ::Azure::Storage::AutoGenerated::ThriftQueueContinuationToken, optional: true }
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, "Required field queueList is unset!") unless @queueList
        end

        ::Thrift::Struct.generate_accessors self
      end
    end
  end
end
