require "azure/storage"
require_relative "core_converter"
require_relative "../utils"
require_relative "../infrastructure/logging_aspect"


module Azure::Storage::Stress
  module Converter
    class FileConverter
      def FileConverter.getFileService(handler, accountInfo, filters = [])
        storageService = XSS::Converter::CoreConverter.getStorageService(handler, accountInfo)
        file_client = storageService.file_client
        filters.each { |filter| file_client.with_filter(filter) }
        file_client
      end

      def self.getRequestOptions(thriftBlobRequestOptions)
        options = XSS::Converter::CoreConverter::getRequestOptions(thriftBlobRequestOptions)
      end

      def self.getFileContinuationToken(nextMarker, uri)
        r = XSS::AutoGenerated::ThriftFileContinuationToken.new
        r.targetLocation = uri.to_s.include?("-secondary") ? XSS::AutoGenerated::StorageLocation::Secondary : XSS::AutoGenerated::StorageLocation::Primary
        r.nextMarker = nextMarker
        r
      end

      def self.buildCloudFileShareResponseFromInternalRequestInfo(rInfo)
        result = XSS::AutoGenerated::CloudFileShareResponse.new
        result.etag = rInfo.responseHeaders["etag"] unless rInfo.responseHeaders["etag"].nil?
        result.lastModified = XSS::Utilities::timeStringToInteger(rInfo.responseHeaders["last-modified"]) unless rInfo.responseHeaders["last-modified"].nil?
        result.metadata = XSS::Utilities::metadataFromHeaders(rInfo.responseHeaders)
        result.snapshotTime = XSS::Utilities::timeStringToInteger(rInfo.responseHeaders["x-ms-snapshot"]) unless rInfo.responseHeaders["x-ms-snapshot"].nil?
        # TODO:
        # result.shareQuota
        result
      end


      def self.buildCloudFileShareResponseFromShare(share)
        result = XSS::AutoGenerated::CloudFileShareResponse.new
        properties = share.properties
        result.etag = properties["etag"] if properties["etag"]
        result.lastModified = XSS::Utilities::timeStringToInteger(properties["last-modified"]) if properties["last-modified"]
        result.metadata = share.metadata
        result.snapshotTime = XSS::Utilities::timeStringToInteger(properties["x-ms-snapshot"]) if properties["x-ms-snapshot"]
        # TODO: Not sure whether this is right
        result.shareQuota = share.quota
        result
      end
      def self.bulidCloudFileDirectoryResponseFromInternalRequestInfo(rInfo)
        result = XSS::AutoGenerated::CloudFileDirectoryResponse.new

        result.etag = rInfo.responseHeaders["etag"] unless rInfo.responseHeaders["etag"].nil?

        result.lastModified = XSS::Utilities::timeStringToInteger(rInfo.responseHeaders["last-modified"]) unless rInfo.responseHeaders["last-modified"].nil?

        result.metadata = XSS::Utilities::metadataFromHeaders(rInfo.responseHeaders)

        result
      end

      def self.bulidCloudFileDirectoryResponseFromFileOrDirectory(fileOrdirectory)
        result = XSS::AutoGenerated::CloudFileDirectoryResponse.new
        properties = fileOrdirectory.properties
        result.etag = properties[:etag] if properties[:etag]
        result.lastModified = XSS::Utilities::timeStringToInteger(properties[:last_modified]) if properties[:last_modified]
        result.metadata = fileOrdirectory.metadata
        result
      end

      def self.buildCloudFileDirectoryListItemWithDirectory(directory, filePath, client)
        result = XSS::AutoGenerated::CloudFileDirectoryListItem.new
        result.name = directory.name
        # TODO: Not sure whether path is right
        directoryPath = "#{filePath.shareName}/#{filePath.directoryName}/#{directory.name}"
        result.uri = XSS::Converter::CoreConverter::getCloudStorageUriWithClientAndPath(client, directoryPath)
        result.properties = self.bulidCloudFileDirectoryResponseFromFileOrDirectory(directory)
        result
      end

      def self.buildCloudFileListItemWithFile(file, filePath, client)
        result = XSS::AutoGenerated::CloudFileListItem.new
        result.name = file.name
        # TODO: Not sure whether path is right
        directoryPath = "#{filePath.shareName}/#{filePath.directoryName}/#{file.name}"
        result.uri = XSS::Converter::CoreConverter::getCloudStorageUriWithClientAndPath(client, directoryPath)
        result.properties = self.bulidCloudFileDirectoryResponseFromFileOrDirectory(file)
        result
      end

      def self.buildShareDetailWithShareAndClient(share, client)
        shareDetails = XSS::AutoGenerated::ShareDetail.new
        shareDetails.cloudStorageUri = XSS::Converter::CoreConverter::getCloudStorageUriWithClientAndPath(client, share.name)
        shareDetails.shareResponse = self.buildCloudFileShareResponseFromShare(share)
        shareDetails
      end
    end
  end
end
