require_relative "base_handler"
require_relative "../utils"
require_relative "../auto_generated/cloud_blob_client_service"
require_relative "../converter/core_converter"
require_relative "../converter/blob_converter"
require_relative "../infrastructure/logging_aspect"


module Azure::Storage::Stress
  module Handler
    class CloudBlobClientHandler < BaseHandler
      def listBlobsSegmented(listBlobsPayload, accountInfo, maxResults, currentToken)
        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        blobClient = self.build_client(internalRequestInfo, accountInfo)
        # ==== Construct Parameters ==== #
        reqInfo = listBlobsPayload.thriftRequestOptions
        options = XSS::Converter::BlobConverter::getRequestOptions(listBlobsPayload.thriftRequestOptions)
        options.merge! XSS::Converter::CoreConverter::getOperationContextOptions(listBlobsPayload.thriftOperationContext)
        options[:prefix] = listBlobsPayload.prefix if listBlobsPayload.prefix
        options[:max_results] = maxResults
        options[:marker] = currentToken.nextMarker
        options[:location_mode] = XSS::Converter::CoreConverter::getLocationModeFromStorageLocation(currentToken.targetLocation)
        # options[:delimiter]?
        # TODO: useFlatBlobListing, listingDetails
        # ==== Operation ==== #
        LoggingAspect::logger.info("Listing blob segmented for container #{containerName}")
        LoggingAspect::logger.debug("'options' is #{options.to_s}")
        result = blobClient.list_blobs(containerName, options)
        # ==== Construct Return Value ==== #
        LoggingAspect::logger.info("Listing blob segmented for container #{containerName} successful")
        r = XSS::AutoGenerated::ListBlobsResponse.new
        r.continuationToken = XSS::Converter::BlobConverter::getBlobContinuationToken(result.continuation_token, internalRequestInfo.uri)
        r.blobList = Array(result)
        r
      end

      def listContainersSegmented(listContainersPayload, accountInfo, maxResults, currentToken)
        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        blobClient = self.build_client(internalRequestInfo, accountInfo)
        # ==== Construct Parameters ==== #
        reqInfo = listContainersPayload.thriftRequestOptions
        options = XSS::Converter::BlobConverter::getRequestOptions(listContainersPayload.thriftRequestOptions)
        options.merge! XSS::Converter::CoreConverter::getOperationContextOptions(listContainersPayload.thriftOperationContext)
        options[:prefix] = listContainersPayload.prefix if listContainersPayload.prefix
        options[:max_results] = maxResults
        options[:marker] = currentToken.nextMarker
        options[:location_mode] = XSS::Converter::CoreConverter::getLocationModeFromStorageLocation(currentToken.targetLocation)
        # options[:delimiter]?
        # TODO: useFlatBlobListing, listingDetails
        # ==== Operation ==== #
        LoggingAspect::logger.info("Listing containers segmented")
        LoggingAspect::logger.debug("'options' is #{options.to_s}")
        result = blobClient.listContainers(options)
        # ==== Construct Return Value ==== #
        LoggingAspect::logger.info("Listing containers successful")
        r = XSS::AutoGenerated::ListContainersResponse.new
        r.continuationToken = XSS::Converter::BlobConverter::getBlobContinuationToken(result.continuation_token, internalRequestInfo.uri)
        r.blobList = Array(result)
        r
      end

      def setProperties(thriftRequestOptions, accountInfo, thriftOperationContext, properties)
        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        blobClient = self.build_client(internalRequestInfo, accountInfo)
        # ==== Construct Parameters ==== #
        reqOptions = XSS::Converter::CoreConverter.getRequestOptions(thriftRequestOptions)
        reqOptions.merge! XSS::Converter::CoreConverter::getOperationContextOptions(thriftOperationContext)
        serviceProperties = XSS::Converter::CoreConverter.convertThriftStorageServicePropertiesToServiceProperties(properties)
        # ==== Operation ==== #
        blobClient.set_service_properties(serviceProperties, reqOptions)
        # ==== Construct Return Value ==== #
        XSS::Converter::BlobConverter::buildBlobContainerResponseFromInternalRequestInfo(internalRequestInfo)
      end

      def getProperties(thriftRequestOptions, accountInfo, thriftOperationContext)
        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        blobClient = self.build_client(internalRequestInfo, accountInfo)
        # ==== Construct Parameters ==== #
        reqOptions = XSS::Converter::CoreConverter.getRequestOptions(thriftRequestOptions)
        reqOptions.merge! XSS::Converter::CoreConverter::getOperationContextOptions(thriftOperationContext)
        # ==== Operation ==== #
        result = blobClient.get_service_properties(reqOptions)
        # ==== Construct Return Value ==== #
        XSS::Converter::CoreConverter.convertServicePropertiesToThriftStorageServiceProperties(temp)
      end


      def getServiceStats(thriftRequestOptions, accountInfo, thriftOperationContext)
        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        blobClient = self.build_client(internalRequestInfo, accountInfo)
        # ==== Construct Parameters ==== #
        options = XSS::Converter::BlobConverter::getRequestOptions(thriftRequestOptions)
        options.merge! XSS::Converter::CoreConverter::getOperationContextOptions(thriftOperationContext)
        # ==== Operation ==== #
        result = blobClient.get_service_stats(reqOptions)
        # ==== Construct Return Value ==== #
        XSS::Converter::CoreConverter.convertGetServiceStatsResultToThriftServiceStats(temp)
      end
    end
  end
end
