require_relative "base_handler"
require_relative "cloud_table_base_handler"
require_relative "../utils"
require_relative "../auto_generated/cloud_table_client_service"
require_relative "../converter/core_converter"
require_relative "../converter/table_converter"
require_relative "../infrastructure/logging_aspect"

module Azure::Storage::Stress
  module Handler
    class CloudTableClientHandler < CloudTableBaseHandler
      def getServiceStats(requestInfo, accountInfo)
        @request_info = XSS::Utilities::get_default_request_info
        tableClient = self.build_client(@request_info, accountInfo)

        # ==== Construct Parameters ==== #
        reqOptions = XSS::Converter::CoreConverter.getRequestOptions(requestInfo.thriftRequestOptions)
        reqOptions.merge! XSS::Converter::CoreConverter::getOperationContextOptions(requestInfo.thriftOperationContext)

        # ==== Operation ==== #
        LoggingAspect::logger.info("Get tables service stats")
        LoggingAspect::logger.debug("'options' is #{reqOptions.to_s}")
        temp = tableClient.get_service_stats(reqOptions)

        # ==== Construct Return Value ==== #
        LoggingAspect::logger.info("Get tables service stats successful")
        result = XSS::Converter::CoreConverter.convertGetServiceStatsResultToThriftServiceStats(temp)
        return result
      end

      def getServiceProperties(requestInfo, accountInfo)
        @request_info = XSS::Utilities::get_default_request_info
        tableClient = self.build_client(@request_info, accountInfo)

        # ==== Construct Parameters ==== #
        reqOptions = XSS::Converter::CoreConverter.getRequestOptions(requestInfo.thriftRequestOptions)
        reqOptions.merge! XSS::Converter::CoreConverter::getOperationContextOptions(requestInfo.thriftOperationContext)

        # ==== Operation ==== #
        LoggingAspect::logger.info("Get table service properties")
        LoggingAspect::logger.debug("'options' is #{reqOptions.to_s}")
        temp = tableClient.get_service_properties(reqOptions)

        # ==== Construct Return Value ==== #
        LoggingAspect::logger.info("Get table service properties successful")
        result = XSS::Converter::CoreConverter.convertServicePropertiesToThriftStorageServiceProperties(temp)
        return result
      end

      def setServiceProperties(serviceProperties, requestInfo, accountInfo)
        @request_info = XSS::Utilities::get_default_request_info
        tableClient = self.build_client(@request_info, accountInfo)

        # ==== Construct Parameters ==== #
        reqOptions = XSS::Converter::CoreConverter.getRequestOptions(requestInfo.thriftRequestOptions)
        reqOptions.merge! XSS::Converter::CoreConverter::getOperationContextOptions(requestInfo.thriftOperationContext)
        serviceProperties = XSS::Converter::CoreConverter.convertThriftStorageServicePropertiesToServiceProperties(properties)

        # ==== Operation ==== #
        LoggingAspect::logger.info("Set table service properties")
        LoggingAspect::logger.debug("'options' is #{reqOptions.to_s}")
        tableClient.set_service_properties(serviceProperties, reqOptions)

        # ==== Construct Return Value ==== #
        LoggingAspect::logger.info("Set table service properties successful")
        return
      end

      def listTables(prefix, requestInfo, accountInfo)
        @request_info = XSS::Utilities::get_default_request_info
        tableClient = self.build_client(@request_info, accountInfo)

        # ==== Construct Parameters ==== #
        reqOptions = XSS::Converter::CoreConverter.getRequestOptions(requestInfo.thriftRequestOptions)
        reqOptions.merge! XSS::Converter::CoreConverter::getOperationContextOptions(requestInfo.thriftOperationContext)

        # ==== Operation ==== #
        entries = []
        begin
          unless temp.nil?
            reqOptions[:next_table_token] = temp.continuation_token
          end
          LoggingAspect::logger.info("Listing tables")
          LoggingAspect::logger.debug("'options' is #{reqOptions.to_s}")
          temp = tableClient.list_tables(reqOptions)
          temp.each do |table|
            entry = XSS::AutoGenerated::ListTableItem.new
            entry.name = table["TableName"]
            entry.storageUri = XSS::Converter::CoreConverter::getCloudStorageUriWithClientAndPath(tableClient, entry.name)
            entries.push(entry)
          end
        end while !temp.nil? && !temp.continuation_token.nil?

        # ==== Construct Return Value ==== #
        LoggingAspect::logger.info("Listing tables successful")
        result = XSS::AutoGenerated::ListTableResultSegmented.new
        result.results = entries
        return result
      end

      def ListTableSegmented(prefix, maxResults, continuationToken, requestInfo, accountInfo)
        @request_info = XSS::Utilities::get_default_request_info
        tableClient = self.build_client(@request_info, accountInfo)

        # ==== Construct Parameters ==== #
        reqOptions = XSS::Converter::CoreConverter.getRequestOptions(requestInfo.thriftRequestOptions)
        reqOptions.merge! XSS::Converter::CoreConverter::getOperationContextOptions(requestInfo.thriftOperationContext)
        reqOptions[:next_table_token] = continuationToken.nextTableName if continuationToken
        unless continuationToken.nil? || continuationToken.targetLocation.nil?
          reqOptions[:location_mode] = XSS::Converter::CoreConverter::getLocationModeFromStorageLocation(currentToken.targetLocation)
        end

        # ==== Operation ==== #
        LoggingAspect::logger.info("Listing tables segmented")
        LoggingAspect::logger.debug("'options' is #{reqOptions.to_s}")
        temp = tableClient.query_tables(reqOptions)

        # ==== Construct Return Value ==== #
        entries = []
        temp.each do |table|
          entry = XSS::AutoGenerated::ListTableItem.new
          entry.name = table["TableName"]
          entry.storageUri = XSS::Converter::CoreConverter::getCloudStorageUriWithClientAndPath(tableClient, entry.name)
          entries.push(entry)
        end
        LoggingAspect::logger.info("Listing tables segmented successful")
        result = XSS::AutoGenerated::ListTableResultSegmented.new
        result.continuationToken = XSS::AutoGenerated::ThriftTableContinuationToken.new
        result.continuationToken.nextTableName = temp.continuation_token
        result.results = entries
        return result
      end
    end
  end
end
