require_relative "base_handler"
require_relative "cloud_queue_base_handler"
require_relative "../utils"
require_relative "../auto_generated/cloud_queue_client_service"
require_relative "../converter/core_converter"
require_relative "../converter/queue_converter"
require_relative "../infrastructure/logging_aspect"


module Azure::Storage::Stress
  module Handler
    class CloudQueueClientHandler < CloudQueueBaseHandler
      def listQueues(listQueuesPayload, accountInfo)
        # ==== Construct Return Value ==== #
        result = XSS::AutoGenerated::ListQueuesResponse.new
        result.queueList = entries
        return result

        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        queueClient = self.build_client(internalRequestInfo, accountInfo)
        # ==== Construct Parameters ==== #
        options = XSS::Converter::CoreConverter::getRequestOptions(listQueuesPayload.requestOptions)
        options.merge! XSS::Converter::CoreConverter::getOperationContextOptions(listQueuesPayload.thriftOperationContext)
        options[:metadata] = true if listQueuesPayload.detailsIncluded == XSS::AutoGenerated::ThriftQueueListingDetails::Metadata
        options[:prefix] = listQueuesPayload.prefix if listQueuesPayload.prefix
        # ==== Operation ==== #
        r = XSS::AutoGenerated::ListQueuesResponse.new
        r.queueList = []
        LoggingAspect::info("Listing queues")
        nextMarker = nil
        # Recursive list
        loop do
          options[:marker] = nextMarker if nextMarker
          LoggingAspect::debug("'options' is #{options.to_s}")
          result = queueClient.list_queues(options)
          # ==== Construct Return Value ==== #
          result.each { |queue| r.queueList.push XSS::Converter::QueueConverter::buildCloudQueueResponseFromQueueAndClient(queue, queueClient) }
          nextMarker = result.continuation_token
          break unless nextMarker && !nextMarker.empty?
        end
        LoggingAspect::info("Listing containers successful")
        r
      end

      def listQueuesSegmented(listQueuesPayload, accountInfo, maxResults, currentToken)
        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        queueClient = self.build_client(internalRequestInfo, accountInfo)
        # ==== Construct Parameters ==== #
        options = XSS::Converter::BlobConverter::getRequestOptions(listQueuesPayload.thriftRequestOptions)
        options.merge! XSS::Converter::CoreConverter::getOperationContextOptions(listQueuesPayload.thriftOperationContext)
        options.merge! XSS::Converter::BlobConverter::getListDetailOptionsFromBlobContainerListingDetails(listQueuesPayload.containerListingDetails)
        options[:prefix] = listQueuesPayload.prefix if listQueuesPayload.prefix
        options[:metadata] = true if listQueuesPayload.detailsIncluded == XSS::AutoGenerated::ThriftQueueListingDetails::Metadata
        options[:max_results] = maxResults
        options[:marker] = currentToken.nextMarker
        options[:location_mode] = XSS::Converter::CoreConverter::getLocationModeFromStorageLocation(currentToken.targetLocation)
        # ==== Operation ==== #
        LoggingAspect::info("Listing queues segmented")
        LoggingAspect::debug("'options' is #{options.to_s}")
        result = queueClient.list_queues(reqOptions)
        # ==== Construct Return Value ==== #
        LoggingAspect::info("Listing queues successful")
        r = XSS::AutoGenerated::ListContainersResponse.new
        r.continuationToken = XSS::Converter::QueueConverter::getQueueContinuationToken(result.continuation_token, internalRequestInfo.uri)
        r.containerList = []
        result.each { |queue| r.queueList.push XSS::Converter::QueueConverter::buildCloudQueueResponseFromQueueAndClient(queue, queueClient) }
        r

        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        queueClient = self.build_client(internalRequestInfo, accountInfo)
        # ==== Construct Parameters ==== #
        reqOptions = XSS::Converter::CoreConverter.getRequestOptions(listQueuesPayload.requestOptions)
        reqOptions.merge! XSS::Converter::CoreConverter::getOperationContextOptions(requestInfo.thriftOperationContext)
        reqOptions[:prefix] = listQueuesPayload.prefix unless listQueuesPayload.prefix.nil?
        reqOptions[:metadata] = true if listQueuesPayload.detailsIncluded == XSS::AutoGenerated::ThriftQueueListingDetails::Metadata
        reqOptions[:max_results] = maxResults
        reqOptions[:marker] = currentToken.nextMarker
        # XSS::Infrastructure::LoggingAspect.logger.debug reqOptions

        # ==== Operation ==== #
        temp = queueClient.list_queues(reqOptions)

        # ==== Construct Return Value ==== #
        entries = []
        temp.each do |queue|
          entry = XSS::AutoGenerated::CloudQueueResponse.new
          entry.name = queue.name
          entry.metadata = queue.metadata
          # TODO storageURI
          entries.push(entry)
        end
        result = XSS::AutoGenerated::ListQueuesResponse.new
        result.continuationToken.nextMarker = temp.continuation_token
        result.queueList = entries
        return result
      end

      def setProperties(thriftRequestOptions, accountInfo, thriftOperationContext, properties)
        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        queueClient = self.build_client(internalRequestInfo, accountInfo)
        # ==== Construct Parameters ==== #
        options = XSS::Converter::CoreConverter.getRequestOptions(thriftRequestOptions)
        options.merge! XSS::Converter::CoreConverter::getOperationContextOptions(thriftOperationContext)
        serviceProperties = XSS::Converter::CoreConverter.convertThriftStorageServicePropertiesToServiceProperties(properties)
        # ==== Operation ==== #
        LoggingAspect::info("Setting service properties")
        LoggingAspect::debug("'options' is #{options.to_s}")
        queueClient.set_service_properties(serviceProperties, options)
        # ==== Construct Return Value ==== #
        LoggingAspect::info("Setting service properties successful")
        XSS::Converter::BlobConverter::buildBlobContainerResponseFromInternalRequestInfo(internalRequestInfo)
      end

      def getProperties(thriftRequestOptions, thriftOperationContext, accountInfo)
        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        queueClient = self.build_client(internalRequestInfo, accountInfo)
        # ==== Construct Parameters ==== #
        reqOptions = XSS::Converter::CoreConverter.getRequestOptions(thriftRequestOptions)
        reqOptions.merge! XSS::Converter::CoreConverter::getOperationContextOptions(thriftOperationContext)
        # ==== Operation ==== #
        LoggingAspect::info("Getting service properties")
        LoggingAspect::debug("'options' is #{reqOptions.to_s}")
        result = queueClient.get_service_properties(reqOptions)
        # ==== Construct Return Value ==== #
        LoggingAspect::info("Getting service properties")
        # ==== Construct Return Value ==== #
        XSS::Converter::CoreConverter.convertServicePropertiesToThriftStorageServiceProperties(result)
      end

      def getServiceStats(thriftRequestOptions, thriftOperationContext, accountInfo)
        # ==== Build Client ==== #
        internalRequestInfo = XSS::Utilities::get_default_request_info
        queueClient = self.build_client(internalRequestInfo, accountInfo)
        reqOptions = XSS::Converter::CoreConverter::getRequestOptions(thriftRequestOptions)
        reqOptions.merge! XSS::Converter::CoreConverter::getOperationContextOptions(thriftOperationContext)
        # ==== Operation ==== #
        LoggingAspect::info("Getting service status")
        LoggingAspect::debug("'options' is #{reqOptions.to_s}")
        result = queueClient.get_service_stats(reqOptions)
        # ==== Construct Return Value ==== #
        LoggingAspect::info("Getting service status successful")
        XSS::Converter::CoreConverter.convertGetServiceStatsResultToThriftServiceStats(result)
      end
    end
  end
end
