#
# Auto-generated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require "thrift"
require_relative "blob_types"
require_relative "cloud_blob_client_types"
require_relative "cloud_blob_container_types"
require_relative "cloud_file_types"
require_relative "cloud_file_client_types"
require_relative "cloud_file_directory_types"
require_relative "cloud_file_share_types"
require_relative "cloud_queue_types"
require_relative "cloud_queue_client_types"
require_relative "cloud_table_types"
