#
# Auto-generated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require "thrift"
require_relative "core_types"
require_relative "table_types_types"


module Azure::Storage::Stress
  module AutoGenerated
    class TableRequestInfo
      include ::Thrift::Struct, ::Thrift::Struct_Union
      TABLENAME = 1
      THRIFTREQUESTOPTIONS = 2
      THRIFTOPERATIONCONTEXT = 3

      FIELDS = {
        TABLENAME => { type: ::Thrift::Types::STRING, name: "tableName", optional: true },
        THRIFTREQUESTOPTIONS => { type: ::Thrift::Types::STRUCT, name: "thriftRequestOptions", class: ::XSS::AutoGenerated::ThriftTableRequestOptions, optional: true },
        THRIFTOPERATIONCONTEXT => { type: ::Thrift::Types::STRUCT, name: "thriftOperationContext", class: ::XSS::AutoGenerated::OperationContext, optional: true }
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end
  end
end
