#
# Auto-generated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require "rubygems"
require "thrift"
require_relative "core_types"
require_relative "blob_types_types"


module Azure
  module Storage
    module AutoGenerated
      class ListContainersResponse
        include ::Thrift::Struct, ::Thrift::Struct_Union
        CONTAINERLIST = 1
        CONTINUATIONTOKEN = 2

        FIELDS = {
          CONTAINERLIST => { type: ::Thrift::Types::LIST, name: "containerList", element: { type: ::Thrift::Types::STRUCT, class: ::Azure::Storage::AutoGenerated::ThriftCloudBlobContainer } },
          CONTINUATIONTOKEN => { type: ::Thrift::Types::STRUCT, name: "continuationToken", class: ::Azure::Storage::AutoGenerated::ThriftBlobContinuationToken, optional: true }
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, "Required field containerList is unset!") unless @containerList
        end

        ::Thrift::Struct.generate_accessors self
      end
    end
  end
end
