#
# Auto-generated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require "rubygems"
require "thrift"
require_relative "core_types"

module Azure::Storage::Stress
  module AutoGenerated
    LONG_NOT_PASSED = -1

    TIMESPAN_NOT_PASSED = -1

    INT_NOT_PASSED = -1

    DEFAULT_VISIBILITY_DELAY = 0

    DEFAULT_TIME_TO_LIVE = 604800

    TRUE_VALUE = "1"

    FALSE_VALUE = "0"

    NEXT_TABLE_NAME = "NextTableName"

    NEXT_PARTITION_KEY = "NextPartitionKey"

    NEXT_ROW_KEY = "NextRowKey"

    Service_SupportedFeatures = "SupportedFeatures"

    Service_CloudBlobContainer = "CloudBlobContainer"

    Service_CloudBlob = "CloudBlob"

    Service_CloudPageBlob = "CloudPageBlob"

    Service_CloudBlockBlob = "CloudBlockBlob"

    Service_CloudAppendBlob = "CloudAppendBlob"

    Service_CloudBlobClient = "CloudBlobClient"

    Service_CloudFile = "CloudFile"

    Service_CloudFileDirectory = "CloudFileDirectory"

    Service_CloudFileShare = "CloudFileShare"

    Service_CloudFileClient = "CloudFileClient"

    Service_CloudTable = "CloudTable"

    Service_CloudTableClient = "CloudTableClient"

    Service_CloudQueue = "CloudQueue"

    Service_CloudQueueClient = "CloudQueueClient"
  end
end
